# Generated by Django 6.0.1 on 2026-02-20 15:31

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('project_of_interest', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The official name of the project.', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title. Auto-generated.', max_length=220, unique=True)),
                ('location', models.CharField(help_text="General area, e.g., 'Vesu, Surat'", max_length=100)),
                ('address', models.CharField(default='', help_text='Full address for display and maps.', max_length=255)),
                ('description', models.TextField(help_text='Detailed project description for the showcase page.')),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('CLUB', 'Lifestyle Club')], default='RESIDENTIAL', max_length=20)),
                ('status', models.CharField(choices=[('ONGOING', 'On-going'), ('COMPLETED', 'Completed'), ('UPCOMING', 'Upcoming'), ('OPERATIONAL', 'Operational')], default='ONGOING', max_length=20)),
                ('badge_text', models.CharField(blank=True, help_text="Optional text for a custom badge, e.g., 'New Launch', 'Premium', 'Sold Out'.", max_length=50, null=True)),
                ('badge_bg_color', models.CharField(default='#eab308', help_text='Hex color code for the badge background.', max_length=7)),
                ('badge_text_color', models.CharField(default='#000000', help_text='Hex color code for the badge text.', max_length=7)),
                ('highlights', models.JSONField(blank=True, default=dict, help_text="Key-value pairs for project highlights (e.g., {'Configuration': '3 BHK', 'Floors': '14'}).")),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenities strings or a dictionary of categories.')),
                ('show_brochure_section', models.BooleanField(default=True, help_text='Toggle to show/hide the brochure download section.')),
                ('show_amenities_section', models.BooleanField(default=True, help_text='Toggle to show/hide the amenities section.')),
                ('show_gallery_section', models.BooleanField(default=True, help_text='Toggle to show/hide the gallery section.')),
                ('main_image', models.ImageField(help_text='Primary image shown in project listings and cards.', upload_to=api.models.project_directory_path)),
                ('brochure_pdf', models.FileField(blank=True, help_text='Project e-brochure in PDF format.', null=True, upload_to=api.models.project_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('video_url', models.URLField(blank=True, help_text='Link to a YouTube or Vimeo video for embedding.', null=True)),
                ('map_embed_url', models.TextField(blank=True, help_text='Full embed code from Google Maps (the `<iframe>...</iframe>` part).', null=True)),
                ('show_in_nav', models.BooleanField(default=True, help_text='Uncheck to hide this project from the main navigation dropdowns.')),
                ('nav_order', models.PositiveIntegerField(default=0, help_text='Order in which projects appear in the navigation. Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['nav_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="An image for the project's gallery.", upload_to=api.models.project_directory_path)),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for accessibility (screen readers).', max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['id'],
            },
        ),
    ]
