# Generated by Django 6.0.1 on 2026-02-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tagline',
            field=models.CharField(blank=True, help_text="Main highlight for the card (e.g., '3 & 4 BHK Luxury'). Max 100 chars.", max_length=100, null=True),
        ),
    ]
