# Generated by Django 6.0.1 on 2026-02-21 14:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed project description for the showcase page.', verbose_name='Description'),
        ),
    ]
