# Generated by Django 6.0.1 on 2026-02-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False, help_text="Check this box if the project is fully completed. It will show a green 'COMPLETED' stamp on the website."),
        ),
    ]
