# Generated by Django 6.0.1 on 2026-02-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'On-going'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=20),
        ),
    ]
