# Generated by Django 6.0.1 on 2026-02-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.CharField(blank=True, help_text="Specific neighborhood, e.g., 'Vesu', 'Dumas', 'Tukvada'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='bhk',
            field=models.CharField(blank=True, help_text="BHK options for Residential, e.g., '2 BHK, 3 BHK'. Use commas to separate.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, help_text="Type of property, e.g., 'Apartment', 'Villa', 'Office', 'Showroom'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(help_text="City name, e.g., 'Surat', 'Vapi'", max_length=100),
        ),
    ]
