# Generated by Django 6.0.1 on 2026-02-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_area_project_bhk_project_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, help_text="City name for filtering, e.g., 'Surat', 'Vapi'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(help_text="Display location string, e.g., 'Vesu, Surat'", max_length=100),
        ),
    ]
