# Generated by Django 6.0.1 on 2026-02-28 04:17

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jobopening_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Bizz499\\real estate\\awadh\\backend\\private_media'), upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'])]),
        ),
    ]
