# Generated by Django 6.0.1 on 2026-02-28 05:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('media', 'Media')], default='blog', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='insights/')),
                ('content', tinymce.models.HTMLField(blank=True, help_text='Main content for Blogs', null=True)),
                ('short_description', models.TextField(blank=True, help_text='Excerpt for list view')),
                ('media_type', models.CharField(blank=True, help_text='e.g., Award, News, Press', max_length=50)),
                ('external_link', models.URLField(blank=True, help_text='Link for external media coverage', null=True)),
                ('display_size', models.CharField(choices=[('small', 'Small (1x1)'), ('large', 'Large (2x2)'), ('wide', 'Wide (2x1)'), ('tall', 'Tall (1x2)')], default='small', help_text='For Media Section Grid', max_length=10)),
                ('flex_grow', models.FloatField(default=1.0, help_text='For Blog Section Masonry (e.g., 1.0, 1.5, 2.0)')),
                ('background_color', models.CharField(blank=True, help_text='Hex code (e.g., #f0f0f0) for Media cards', max_length=20)),
                ('published_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
