# Generated by Django 6.0.1 on 2026-03-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_badge',
            field=models.BooleanField(default=True, help_text='Uncheck to hide the badge.'),
        ),
    ]
