# Generated by Django 6.0.1 on 2026-03-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_project_show_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area_sqft_max',
            field=models.FloatField(blank=True, help_text='Maximum square footage for Commercial projects. Use same as min if single value.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='area_sqft_min',
            field=models.FloatField(blank=True, help_text='Minimum square footage for Commercial projects.', null=True),
        ),
    ]
