# Generated by Django 6.0.1 on 2026-03-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_area_sqft_max_project_area_sqft_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('CLUB', 'Lifestyle Club')], default='RESIDENTIAL', max_length=20),
        ),
    ]
