# Generated by Django 6.0.1 on 2026-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('FARMVILLE', 'Farmville'), ('CLUB', 'Lifestyle Club')], default='RESIDENTIAL', max_length=20),
        ),
    ]
